#!/usr/bin/env bash
export ORION_FRONTEND_HOST="${ORION_FRONTEND_HOST:-127.0.0.1}"
export ORION_FRONTEND_PORT="${ORION_FRONTEND_PORT:-8092}"
export ORION_DEFAULT_BACKEND="${ORION_DEFAULT_BACKEND:-auto}"
